# Generated by Django 5.1 on 2024-10-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cc_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ccc_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='chat_log_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_mod_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('chat_room', models.CharField(max_length=50)),
                ('chat_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hometown_day_info_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hometown_history_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_num', models.CharField(max_length=20)),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hometown_info_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('shift', models.CharField(max_length=200)),
                ('id_num', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('working', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='iu_love_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='iu_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='line_buy_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('shopId', models.IntegerField()),
                ('point', models.FloatField()),
                ('url', models.TextField()),
                ('image_url', models.TextField()),
                ('transfer_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='man_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mm_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ngag_funny_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=200, null=True)),
                ('article_title', models.CharField(max_length=200, null=True)),
                ('article_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ngag_girl_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=200, null=True)),
                ('article_title', models.CharField(max_length=200, null=True)),
                ('article_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ngag_nsfw_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=200, null=True)),
                ('article_title', models.CharField(max_length=200, null=True)),
                ('article_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='oo_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='password_book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service', models.TextField()),
                ('account', models.TextField()),
                ('password', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pp_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pray_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('pray_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_info_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='yuyan_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
